// Mocks generated by Mockito 5.0.16 from annotations
// in tv_series/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:convert' as _i20;
import 'dart:io' as _i5;
import 'dart:typed_data' as _i21;

import 'package:core/data/datasources/db/database_helper.dart' as _i10;
import 'package:core/data/datasources/watchlist_local_data_source.dart' as _i7;
import 'package:core/data/models/tv/season_detail_model.dart' as _i3;
import 'package:core/data/models/tv/tv_detail_model.dart' as _i2;
import 'package:core/data/models/tv/tv_model.dart' as _i13;
import 'package:core/data/models/watchlist_table.dart' as _i9;
import 'package:core/domain/entities/tv/season_detail.dart' as _i18;
import 'package:core/domain/entities/tv/tv.dart' as _i16;
import 'package:core/domain/entities/tv/tv_detail.dart' as _i17;
import 'package:core/utils/failure.dart' as _i15;
import 'package:core/utils/ssl_pinning.dart' as _i19;
import 'package:dartz/dartz.dart' as _i4;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i11;
import 'package:tv_series/data/datasources/tv_remote_data_source.dart' as _i12;
import 'package:tv_series/domain/repositories/tv_repository.dart' as _i14;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvDetailModel_0 extends _i1.Fake implements _i2.TvDetailModel {}

class _FakeSeasonDetailModel_1 extends _i1.Fake
    implements _i3.SeasonDetailModel {}

class _FakeEither_2<L, R> extends _i1.Fake implements _i4.Either<L, R> {}

class _FakeSecurityContext_3 extends _i1.Fake implements _i5.SecurityContext {}

class _FakeResponse_4 extends _i1.Fake implements _i6.Response {}

class _FakeStreamedResponse_5 extends _i1.Fake implements _i6.StreamedResponse {
}

/// A class which mocks [WatchlistLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLocalDataSource extends _i1.Mock
    implements _i7.WatchlistLocalDataSource {
  MockWatchlistLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i9.WatchlistTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<String> removeWatchlist(_i9.WatchlistTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i9.WatchlistTable?> getWatchlistById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getWatchlistById, [id]),
              returnValue: Future<_i9.WatchlistTable?>.value())
          as _i8.Future<_i9.WatchlistTable?>);
  @override
  _i8.Future<List<_i9.WatchlistTable>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<List<_i9.WatchlistTable>>.value(
              <_i9.WatchlistTable>[])) as _i8.Future<List<_i9.WatchlistTable>>);
  @override
  _i8.Future<List<_i9.WatchlistTable>> getWatchlistTvs() => (super.noSuchMethod(
          Invocation.method(#getWatchlistTvs, []),
          returnValue:
              Future<List<_i9.WatchlistTable>>.value(<_i9.WatchlistTable>[]))
      as _i8.Future<List<_i9.WatchlistTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i10.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i11.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i11.Database?>.value())
          as _i8.Future<_i11.Database?>);
  @override
  _i8.Future<int> insertWatchlist(_i9.WatchlistTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<int> removeWatchlist(_i9.WatchlistTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<Map<String, dynamic>?> getWatchlistById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getWatchlistById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i8.Future<List<Map<String, dynamic>>>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvs, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i8.Future<List<Map<String, dynamic>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i12.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.TvModel>> getNowPlayingTvs() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvs, []),
              returnValue: Future<List<_i13.TvModel>>.value(<_i13.TvModel>[]))
          as _i8.Future<List<_i13.TvModel>>);
  @override
  _i8.Future<List<_i13.TvModel>> getPopularTvs() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvs, []),
              returnValue: Future<List<_i13.TvModel>>.value(<_i13.TvModel>[]))
          as _i8.Future<List<_i13.TvModel>>);
  @override
  _i8.Future<List<_i13.TvModel>> getTopRatedTvs() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvs, []),
              returnValue: Future<List<_i13.TvModel>>.value(<_i13.TvModel>[]))
          as _i8.Future<List<_i13.TvModel>>);
  @override
  _i8.Future<_i2.TvDetailModel> getTvDetail(int? id) => (super.noSuchMethod(
          Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i2.TvDetailModel>.value(_FakeTvDetailModel_0()))
      as _i8.Future<_i2.TvDetailModel>);
  @override
  _i8.Future<List<_i13.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<List<_i13.TvModel>>.value(<_i13.TvModel>[]))
          as _i8.Future<List<_i13.TvModel>>);
  @override
  _i8.Future<List<_i13.TvModel>> searchTvs(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvs, [query]),
              returnValue: Future<List<_i13.TvModel>>.value(<_i13.TvModel>[]))
          as _i8.Future<List<_i13.TvModel>>);
  @override
  _i8.Future<_i3.SeasonDetailModel> getTvSeasonDetail(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getTvSeasonDetail, [id, seasonNumber]),
              returnValue: Future<_i3.SeasonDetailModel>.value(
                  _FakeSeasonDetailModel_1()))
          as _i8.Future<_i3.SeasonDetailModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i14.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.Either<_i15.Failure, List<_i16.Tv>>> getNowPlayingTvs() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvs, []),
          returnValue: Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>.value(
              _FakeEither_2<_i15.Failure, List<_i16.Tv>>())) as _i8
          .Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, List<_i16.Tv>>> getPopularTvs() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvs, []),
          returnValue: Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>.value(
              _FakeEither_2<_i15.Failure, List<_i16.Tv>>())) as _i8
          .Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, List<_i16.Tv>>> getTopRatedTvs() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvs, []),
          returnValue: Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>.value(
              _FakeEither_2<_i15.Failure, List<_i16.Tv>>())) as _i8
          .Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, _i17.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i4.Either<_i15.Failure, _i17.TvDetail>>.value(
              _FakeEither_2<_i15.Failure, _i17.TvDetail>())) as _i8
          .Future<_i4.Either<_i15.Failure, _i17.TvDetail>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, List<_i16.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>.value(
              _FakeEither_2<_i15.Failure, List<_i16.Tv>>())) as _i8
          .Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, List<_i16.Tv>>> searchTvs(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvs, [query]),
          returnValue: Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>.value(
              _FakeEither_2<_i15.Failure, List<_i16.Tv>>())) as _i8
          .Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, String>> saveWatchlist(
          _i17.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tv]),
              returnValue: Future<_i4.Either<_i15.Failure, String>>.value(
                  _FakeEither_2<_i15.Failure, String>()))
          as _i8.Future<_i4.Either<_i15.Failure, String>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, String>> removeWatchlist(
          _i17.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
              returnValue: Future<_i4.Either<_i15.Failure, String>>.value(
                  _FakeEither_2<_i15.Failure, String>()))
          as _i8.Future<_i4.Either<_i15.Failure, String>>);
  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, List<_i16.Tv>>> getWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvs, []),
          returnValue: Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>.value(
              _FakeEither_2<_i15.Failure, List<_i16.Tv>>())) as _i8
          .Future<_i4.Either<_i15.Failure, List<_i16.Tv>>>);
  @override
  _i8.Future<_i4.Either<_i15.Failure, _i18.SeasonDetail>> getTvSeasonDetail(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getTvSeasonDetail, [id, seasonNumber]),
              returnValue:
                  Future<_i4.Either<_i15.Failure, _i18.SeasonDetail>>.value(
                      _FakeEither_2<_i15.Failure, _i18.SeasonDetail>()))
          as _i8.Future<_i4.Either<_i15.Failure, _i18.SeasonDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SSLClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSSLClient extends _i1.Mock implements _i19.SSLClient {
  MockSSLClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.SecurityContext> get globalContext =>
      (super.noSuchMethod(Invocation.getter(#globalContext),
              returnValue:
                  Future<_i5.SecurityContext>.value(_FakeSecurityContext_3()))
          as _i8.Future<_i5.SecurityContext>);
  @override
  _i8.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_4()))
          as _i8.Future<_i6.Response>);
  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i21.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i21.Uint8List>.value(_i21.Uint8List(0)))
          as _i8.Future<_i21.Uint8List>);
  @override
  _i8.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i6.StreamedResponse>.value(_FakeStreamedResponse_5()))
          as _i8.Future<_i6.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
